FROM nginx:latest
MAINTAINER Mantikor <straltsou.siarhei@gmail.com>

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "git", "-y"]
RUN ["git", "clone", "https://github.com/GamerHack/GamerHack.github.io", "/opt/goldhen_server/html"]
COPY index2.html /opt/goldhen_server/html/672
COPY style2.css /opt/goldhen_server/html
RUN sed -i "s%index.html%index.html\nindex2.html\n../style2.css%g" /opt/goldhen_server/html/672/cache.manifest
RUN GH=$(ls /opt/goldhen_server/html/672 | grep goldhen_ | tail -1) && sed -i "s%PLfile=\"GOLDHEN\";%PLfile=\"$GH\";%g" /opt/goldhen_server/html/672/index2.html
RUN ["rm", "-r", "/usr/share/nginx/html"]
RUN ["ln", "-s", "/opt/goldhen_server/html", "/usr/share/nginx/html"]
RUN ["service", "nginx", "restart"]
cd /