version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-hen
      tags:
        - 'gamerhack:latest'
    container_name: 'gamerhack_ps_utils'
    env_file:
      - .env
    ports:
      - "$PORT:80"
  dns-server:
    build:
      context: ./
      dockerfile: Dockerfile-dns
      tags:
        - 'dns-server:latest'
    container_name: dns-server
    hostname: dns-server
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_FORWARDERS=https://1.1.1.1/dns-query, https://1.0.0.1/dns-query #Comma separated list of forwarder addresses.
      - DNS_SERVER_FORWARDER_PROTOCOL=Https #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
    volumes:
      - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

volumes:
    config:
